### ISSUE TITLE
Tables SeenAp and SeenClient are empty.

### ISSUE THREAD

**Issue by davidwowa** [RaulCalvoLaorden/wifi_db#18]
Command: python3 wifi_db.py -d dB.SQLite /wifi --debug 

Also no outputs for debugging :(. 

Thank you.

**Comment by r4ulcl** [comment]
Hi!

Yes, the `--debug` command is not yet implemented. You can use `--verbose` to see how the information is processed for the database. 

Regarding SeenAp and SeenClient, if you are using an older version of aircrack-ng (before 1.6) there are no ".log.csv" files which are processed for those tables. 

Thank you.

**Comment by davidwowa** [comment]
I use airodump-ng 1.7 rev 2c8ff3f5. Is possible to extend table ap and client with detection datetime? 

Thank you.

**Comment by r4ulcl** [comment]
Hello,

Try the dev branch now to see if it works for you, I've been testing it and there were some things wrong that I've fixed. 
I've also added the firstTimeSeen column in APs and Clients, it gets it from the log and the rest of the tables, but it is almost untested. 

If you have any questions, please let me know. 
Thank you very much.

**Comment by davidwowa** [comment]
I have cloned dev brunch, but I have errors :(.![image](https://github.com/r4ulcl/wifi_db/assets/9664105/37a143e5-06c0-4e36-866a-27f6cfcc0ec2)

**Comment by r4ulcl** [comment]
That error is because you install the dependencies as wowa but run python as root (sudo).

**Comment by davidwowa** [comment]
it works, thank you.
